### PR TITLE
add MATLAB readme

### PR DESCRIPTION
**Pull request by melanieveale**
Adding a README for the first MATLAB Base Image

### CODE REVIEW

**Comment by ChuckRIHead** [comment]
@melanieveale I don't see a dockerfile in here, just the readme. Was that on purpuse?

**Comment by melanieveale** [comment]
@ChuckRIHead yes, this is just the README on purpose. The Dockerfile is more sophisticated and less "open-sourcey", e.g. has more supporting scripts and specialized MATLAB stuff, so we didn't think it would actually be useful to people.

**Comment by ChuckRIHead** [comment]
If we don't want to include the docker image here, maybe we provide a link to it from here. That way future FE's can still find it if they come here looking for it.

**Comment by melanieveale** [comment]
Added some more info and made some stylistic edits.

**Comment by johnjoo1** [comment]
lgtm!

**Pull request merged**
